# Generated by Django 4.0.2 on 2022-02-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='status',
            field=models.CharField(choices=[('draft', 'Taslak'), ('published', 'Yayınlanmış'), ('deleted', 'Silindi')], default='draft', max_length=12),
        ),
    ]
