# Generated by Django 4.0.2 on 2022-02-23 20:29

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_alter_page_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=' ', editable=False, populate_from='title', unique=True),
            preserve_default=False,
        ),
    ]
